Repository nutanix-cloud-native/cluster-api-ipam-provider-nutanix, pull requests merged in 2024-12, with the labels that each got.

#42 feat: Add CLI tool to reserve and unreserve IP addresses
  .goreleaser.yml
  README.md
  cmd/caipamx/client_params.go
  cmd/caipamx/main.go
  cmd/caipamx/reserve.go
  cmd/caipamx/unreserve.go
  cmd/controller/main.go
  go.mod
  go.sum
  internal/client/networking.go
  internal/controllers/ipaddressclaim.go
  internal/controllers/ipaddressclaim_test.go
  internal/controllers/mockclient/mock_client.go
  internal/poolutil/pool.go
Labels: feature

#38 release(main): v0.3.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#43 build: Fix up release archives
  .goreleaser.yml
  go.mod
Labels: feature

#44 release(main): v0.3.1
  .release-please-manifest.json
  CHANGELOG.md
  docs/hugo.toml
Labels: autorelease: pending

#50 release(main): v0.4.0
  .release-please-manifest.json
  CHANGELOG.md
  README.md
  docs/hugo.toml
Labels: autorelease: pending

#51 fix: getByExt incorrectly expecting pointers
  internal/client/cluster.go
  internal/client/networking.go
Labels: fix

#58 feat: Add verbose flag and hide API calls by default
  cmd/caipamx/main.go
Labels: feature
